# Generated by Django 6.0.3 on 2026-06-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginrecord',
            name='logout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
