# Generated by Django 6.0.3 on 2026-03-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_loginrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginrecord',
            name='ip_address',
            field=models.CharField(default='0.0.0.0', max_length=20),
            preserve_default=False,
        ),
    ]
