# Generated by Django 6.0.3 on 2026-03-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_pc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pc',
            name='last_seen',
        ),
        migrations.AddField(
            model_name='pc',
            name='ip',
            field=models.CharField(default='0.0.0.0', max_length=50),
        ),
        migrations.AlterField(
            model_name='pc',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='pc',
            name='status',
            field=models.CharField(default='offline', max_length=20),
        ),
    ]
