# Generated by Django 6.0.3 on 2026-03-27 09:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0007_remove_pc_last_seen_pc_ip_alter_pc_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pc',
            name='last_seen',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
