# Generated by Django 6.0.3 on 2026-06-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='pc_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='loginrecord',
            name='pc_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pc',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
